# Title
title: Использование Eclipse

# Description (~160 symbols)
description: >
  Настройка рабочего пространства для разраобтки модов с помощью IDE Eclipse.

# Contributors
contributors:
  -
    name: CMTV
    role: Автор
    github: https://github.com/CMTV