api-name: Forge

categories-order:
  - prep
  - base
  - item
  - block
  - tileentity
  - creativetab
  - lang
  - events
  - craftsmeltingandbrewing
  - achievements
  - plant
#  - gui
#  - sounds
#  - entities
#  - world
  - advanced
  - other
