# Title
title: Использование Idea

# Description (~160 symbols)
description: >
  Настройка рабочего пространства для разраобтки модов с помощью IDE Idea.

# Contributors
contributors:
  -
    name: CMTV
    role: Автор
    github: https://github.com/CMTV